### ISSUE TITLE
Some units wont spawn when save file is loaded, causing occupied zones becomes neutral

### ISSUE THREAD

**Issue by GoldJohnKing** [Dzsek/zoneCommander#12]
As the title said, some units would not spawn when the save is loaded, causing the occupied zone lost then becomes neutral

Seems that on every time the issue occurs, the server log printed this:

```
2022-09-22 16:31:29.961 ERROR   SCRIPTING: MIST|teleportToPoint|4135: Point supplied in variable table is not a valid coordinate. Valid coords: { [1] = "LAND", [2] = "ROAD", }
```

Any ideas about that?

**Comment by Dzsek** [comment]
This issue appears when mist is trying to spawn a group and it can't find a valid point on the map to spawn it on.

The list at the end specifies that only LAND and ROAD surface types are allowed for this group. Mist will attempt to generate several points until it finds a valid point within the zone, it will attempt this about 1000 times before it gives up.

If you have a zone that covers both land and water, this error can happen frequently.
As mitigation you can try refining your zones to areas where it is very likely that mist can find a valid point on.
