### ISSUE TITLE
Max Number of Zones

### ISSUE THREAD

**Issue by DrTeemo** [Dzsek/zoneCommander#13]
Is there a limit on how many zones we can have on a map?
I'm trying to add a number of zones to my map, but it seems that after ~30 zones, new zones do not appear on the map.

**Comment by Dzsek** [comment]
There is no limit. Foothold Syria has about 40 zones.

**Comment by DrTeemo** [comment]
Thank you, I'm having issues going more zones to populate, but i'll revisit my implementation to see what's wrong.
