### ISSUE TITLE
killed units on runways

### ISSUE THREAD

**Issue by Barracudas82** [Dzsek/zoneCommander#6]
![image](https://user-images.githubusercontent.com/101940873/161456994-3d7c7a06-1eed-4437-88c6-38d9d0d83a80.png)
Hello, is there any way to clean the runways after a wee while of any ground unit it´s been destroyed on them? It´s preventing the CAP and AWACS flights to do their task. Not worried about the crater as they are repaired in an hour. But the killed units stay till the mission is restarted. Thank you

**Comment by Dzsek** [comment]
DCS does not provide a way of clearing wreckage at the current time. This was requested a few times over the years but ED has yet to address the issue.

For now the only way to clear wreckage is to restart the server.
