### ISSUE TITLE
Units spawning in forests and buildings

### ISSUE THREAD

**Issue by ozdeadmeat** [Dzsek/zoneCommander#8]
Issue: Enemy units spawning in forests and buildings making it difficult to identify as well as destroy as in many cases the trees absorb the weapon detination.

Possible Solution: Remove the map objects in zone where the units are spawning.

**Comment by Dzsek** [comment]
There is already a solution implemented in the form of subzones, which can be used to specify clear spawn areas, while preserving the original zone for all other functions.

**Comment by ozdeadmeat** [comment]
Sweet, thnx mate.
